name: HypwnLab
description: HypwnLab Blog
meta_description: "Nondisclosure 1-day & 0-day research group"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 10
baseurl: /
domain_name: "https://page-tester.github.io/"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "hypwnlab"

# Disqus config
disqus-shortname: ""

future: true